## Exercise 4 - Pandas part 1
- Use *earthquake.csv* file from data_files directory in this exercise. **Important:** Edit the original DataFrame throughout this whole notebook!

1 Read the data from the csv file and create a DataFrame from it.

2 Remove the following columns from the DataFrame: *Magnitude Seismic Stations*, *Azimuthal Gap*, *Horizontal Distance* and *Horizontal Error*.

3 Filter data from the DataFrame so that only rows matching the following criteria will be shown:
    - Source must be US
    - Magnitude value must be over 7.8
    - ID value must start with the string "USP0007"

4 Create a new column to the tenth column position called Grade which will have values from the following formula: ("Magnitude" * "Depth") / "Root Mean Square". Results in this column should be presented with three decimals.

In [1]:
# 1) Read the csv file and create a DataFrame from it.

import pandas as pd

quakes = pd.read_csv("data_files/earthquakes.csv",delimiter=",")

quakes.tail()

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,...,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
23407,12/28/2016,08:22:12,38.3917,-118.8941,Earthquake,12.30,1.2,40.0,5.6,ML,...,18.0,42.47,0.120,NaN,0.1898,NN00570710,NN,NN,NN,Reviewed
23408,12/28/2016,09:13:47,38.3777,-118.8957,Earthquake,8.80,2.0,33.0,5.5,ML,...,18.0,48.58,0.129,NaN,0.2187,NN00570744,NN,NN,NN,Reviewed
23409,12/28/2016,12:38:51,36.9179,140.4262,Earthquake,10.00,1.8,NaN,5.9,MWW,...,NaN,91.00,0.992,4.8,1.5200,US10007NAF,US,US,US,Reviewed
23410,12/29/2016,22:30:19,-9.0283,118.6639,Earthquake,79.00,1.8,NaN,6.3,MWW,...,NaN,26.00,3.553,6.0,1.4300,US10007NL0,US,US,US,Reviewed
23411,12/30/2016,20:08:28,37.3973,141.4103,Earthquake,11.94,2.2,NaN,5.5,MB,...,428.0,97.00,0.681,4.5,0.9100,US10007NTD,US,US,US,Reviewed

In [2]:
# 2) Remove columns: Magnitude Seismic Stations, Azimuthal Gap, Horizontal Distance and Horizontal Error.

quakes.drop(["Magnitude Seismic Stations", "Azimuthal Gap", "Horizontal Distance", "Horizontal Error"],inplace=True,axis=1)
quakes.tail()

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,Magnitude Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
23407,12/28/2016,08:22:12,38.3917,-118.8941,Earthquake,12.30,1.2,40.0,5.6,ML,0.320,0.1898,NN00570710,NN,NN,NN,Reviewed
23408,12/28/2016,09:13:47,38.3777,-118.8957,Earthquake,8.80,2.0,33.0,5.5,ML,0.260,0.2187,NN00570744,NN,NN,NN,Reviewed
23409,12/28/2016,12:38:51,36.9179,140.4262,Earthquake,10.00,1.8,NaN,5.9,MWW,NaN,1.5200,US10007NAF,US,US,US,Reviewed
23410,12/29/2016,22:30:19,-9.0283,118.6639,Earthquake,79.00,1.8,NaN,6.3,MWW,NaN,1.4300,US10007NL0,US,US,US,Reviewed
23411,12/30/2016,20:08:28,37.3973,141.4103,Earthquake,11.94,2.2,NaN,5.5,MB,0.029,0.9100,US10007NTD,US,US,US,Reviewed

In [3]:
# 3) Filter data from the DataFrame so that only rows matching the following criteria will be shown:
# - Source must be US
# - Magnitude value must be over 7.8
#- ID value must start with the string "USP0007"

#quakes[ (quakes.Source == 'US') & (quakes.Magnitude > 7.8) & (quakes.ID[:6] == 'USP0007') ]

#blake = quakes[quakes.Source == 'US']
#blake = quakes[quakes.Magnitude > 7.8]
#blake = quakes[(quakes.Source == 'US') & (quakes.Magnitude > 7.8)]

#blake = quakes.Magnitude  #.loc( lambda x : x > 7.8 )

#blake = quakes[ (quakes["Magnitude"] > 7.8) & (quakes["ID"][:6] == "USP0007") ]

#blake = quakes[ (quakes["ID"].isin(["USP0007"])) ]

#blake = quakes[ quakes["ID"].str.startswith('USP0007') == True ] WORKS!

#blake

quakes = quakes[ (quakes.Source == 'US') & (quakes.Magnitude > 7.8) & (quakes["ID"].str.startswith('USP0007') == True) ]

quakes

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,Magnitude Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
12571,07/30/1995,05:11:24,-23.340,-70.294,Earthquake,45.6,NaN,NaN,8.0,MW,NaN,1.1,USP000714T,US,US,HRV,Reviewed
12703,10/09/1995,15:35:54,19.055,-104.205,Earthquake,33.0,NaN,NaN,8.0,MW,NaN,1.3,USP00074VC,US,US,HRV,Reviewed
12781,12/03/1995,18:01:09,44.663,149.300,Earthquake,33.0,NaN,NaN,7.9,MW,NaN,1.1,USP000782N,US,US,HRV,Reviewed
12838,01/01/1996,08:05:11,0.729,119.931,Earthquake,24.0,NaN,NaN,7.9,MW,NaN,1.2,USP00079ZV,US,US,HRV,Reviewed
12892,02/17/1996,05:59:31,-0.891,136.952,Earthquake,33.0,NaN,NaN,8.2,MW,NaN,1.3,USP0007D1W,US,US,HRV,Reviewed
13059,06/10/1996,04:03:35,51.564,-177.632,Earthquake,33.0,NaN,NaN,7.9,MWC,NaN,0.9,USP0007JCU,US,US,HRV,Reviewed
13076,06/17/1996,11:22:19,-7.137,122.589,Earthquake,587.3,NaN,NaN,7.9,MWC,NaN,1.2,USP0007JW8,US,US,HRV,Reviewed

In [4]:
# 4) Create a new column to the tenth column position called Grade which will have values from the following formula:
# ("Magnitude" * "Depth") / "Root Mean Square".
# Results in this column should be presented with three decimals.

quakes.insert(10, "Grade", round(quakes["Magnitude"]*quakes["Depth"]/quakes["Root Mean Square"],3), True)

quakes

# I wasn't sure if this was supposed to be done on the whole original df, or the filtered version from the previous task.

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,Grade,Magnitude Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
12571,07/30/1995,05:11:24,-23.340,-70.294,Earthquake,45.6,NaN,NaN,8.0,MW,331.636,NaN,1.1,USP000714T,US,US,HRV,Reviewed
12703,10/09/1995,15:35:54,19.055,-104.205,Earthquake,33.0,NaN,NaN,8.0,MW,203.077,NaN,1.3,USP00074VC,US,US,HRV,Reviewed
12781,12/03/1995,18:01:09,44.663,149.300,Earthquake,33.0,NaN,NaN,7.9,MW,237.000,NaN,1.1,USP000782N,US,US,HRV,Reviewed
12838,01/01/1996,08:05:11,0.729,119.931,Earthquake,24.0,NaN,NaN,7.9,MW,158.000,NaN,1.2,USP00079ZV,US,US,HRV,Reviewed
12892,02/17/1996,05:59:31,-0.891,136.952,Earthquake,33.0,NaN,NaN,8.2,MW,208.154,NaN,1.3,USP0007D1W,US,US,HRV,Reviewed
13059,06/10/1996,04:03:35,51.564,-177.632,Earthquake,33.0,NaN,NaN,7.9,MWC,289.667,NaN,0.9,USP0007JCU,US,US,HRV,Reviewed
13076,06/17/1996,11:22:19,-7.137,122.589,Earthquake,587.3,NaN,NaN,7.9,MWC,3866.392,NaN,1.2,USP0007JW8,US,US,HRV,Reviewed

In [5]:
# Just testing an example.

import pandas as pd

# DataFrame creation
disc_golf_data = pd.DataFrame({
    "name": ["Mike","Mike","Mike","Steve","Steve","Steve"],
    "hole_1": [3,2,3,2,2,2],
    "hole_2": [2,2,2,3,2,2],
    "hole_3": [3,4,5,5,4,4],
    "hole_4": [3,3,5,3,3,4],
    "hole_5": [5,6,4,5,3,4]
})

# Add total score column at the end
disc_golf_data["score"] = disc_golf_data.iloc[:,1:].sum(axis=1)

#disc_golf_data
# Group the data by player name and calculate the mean value
#disc_golf_data.groupby("name").mean()